[package]
name = "hammeregg_backend"
version = "0.1.0"
authors = ["Arc-blroth <45273859+Arc-blroth@users.noreply.github.com>"]
edition = "2021"

[dependencies]
eframe = "0.14.0"
names = { git = "https://github.com/fnichol/names", rev = "630a946" }